// Figma TEXT → LSML `text` (§4.4).
//
// The `bind.value` on the text primitive comes from the layer-name `[bind:...]`
// convention (see src/export/bindings.ts). When no binding is declared, the
// node's literal `characters` becomes the static value via the i18n-fallback
// pattern : we emit `metadata.literal` so authoring is round-trippable, and
// the runtime renders `characters` only when no binding is present.
//
// LSML 1.1 doesn't have a "static text" field — the canonical pattern is to
// emit a string LeafPath under `defaults.<auto-generated-path>`. For v0.1 we
// keep things simple : if a `[bind:value=...]` is present, we emit the bind ;
// otherwise we put the static string under `bind.value` is impossible (LeafPath
// must be a path, not a literal). So we synthesise a leaf path and have the
// caller (`bundle.ts`) plant the literal under `defaults`.

import type { TextPrimitive, TextStyle } from "~shared/lsml-types";
import { paintToSolidCss, type FigmaPaint } from "./color";
import { extractUniversal } from "./universal";
import { parseLayerName } from "../export/bindings";
import { PLUGIN_DATA_KEYS, PLUGIN_DATA_NAMESPACE } from "~shared/constants";
import type { MappingResult } from "./types";

interface MockTextNode {
  type: "TEXT";
  id: string;
  name: string;
  characters: string;
  width?: number;
  height?: number;
  fontSize?: number;
  fontWeight?: number;
  fontName?: { family: string; style: string };
  fills?: FigmaPaint[];
  textAlignHorizontal?: "LEFT" | "CENTER" | "RIGHT" | "JUSTIFIED";
  lineHeight?: { unit: "PIXELS" | "PERCENT" | "AUTO"; value?: number };
  letterSpacing?: { unit: "PIXELS" | "PERCENT"; value: number };
  visible?: boolean;
  opacity?: number;
  rotation?: number;
  layoutSizingHorizontal?: "FIXED" | "HUG" | "FILL";
  layoutSizingVertical?: "FIXED" | "HUG" | "FILL";
  /** Plugin data accessor (Figma SceneNode / mock surface). */
  getSharedPluginData?(namespace: string, key: string): string;
}

const ALIGN_MAP: Record<string, TextStyle["textAlign"]> = {
  LEFT: "left",
  CENTER: "center",
  RIGHT: "right",
  JUSTIFIED: "justify",
};

export function mapText(node: MockTextNode): MappingResult {
  const parsed = parseLayerName(node.name, { primitiveKind: "text" });
  const style = extractStyle(node);

  // Roundtrip stability : when the node was just re-imported, plugin data
  // carries the original synthesised __lit.* path. Use it instead of the
  // node-id-derived synthesis (which would otherwise drift across imports).
  const preserved = readPluginData(node, PLUGIN_DATA_KEYS.litBindValue);
  const litPath = preserved ?? synthLiteralPath(node.id);

  const prim: TextPrimitive = {
    kind: "text",
    bind: parsed.bind ?? { value: litPath },
    ...extractUniversal(node),
  };
  if (Object.keys(style).length > 0) prim.style = style;
  if (parsed.bindStyle) prim.bindStyle = parsed.bindStyle;
  if (parsed.bindUniversal) prim.bindUniversal = parsed.bindUniversal;

  // When no [bind:...] directive is present, the node's `characters` is the
  // static text. We surface it via a synthesised leaf path that the bundle
  // assembler plants under `defaults`.
  if (!parsed.bind) {
    return {
      node: prim,
      defaults: { [litPath]: node.characters },
    };
  }
  return { node: prim };
}

function readPluginData(node: MockTextNode, key: string): string | null {
  if (typeof node.getSharedPluginData !== "function") return null;
  const v = node.getSharedPluginData(PLUGIN_DATA_NAMESPACE, key);
  return v === "" ? null : v;
}

export function synthLiteralPath(id: string): string {
  // Stable leaf path for static text. Two synthesis rules :
  //   - prefix : `__lit.text.` (reserved prefix, never collides with __inputs)
  //   - body   : Figma node id with non-path chars replaced by `_`
  return `__lit.text.${id.replace(/[^A-Za-z0-9_]/g, "_")}`;
}

function extractStyle(node: MockTextNode): TextStyle {
  const style: TextStyle = {};
  if (node.fontSize !== undefined) style.fontSize = node.fontSize;
  if (node.fontWeight !== undefined) style.fontWeight = node.fontWeight;
  if (node.fontName?.family) style.fontFamily = node.fontName.family;
  if (node.fontName?.style && /italic/i.test(node.fontName.style)) style.fontStyle = "italic";

  const fill = (node.fills ?? []).find((p) => p.type === "SOLID");
  if (fill) {
    const css = paintToSolidCss(fill);
    if (css) style.color = css;
  }

  const align = node.textAlignHorizontal && ALIGN_MAP[node.textAlignHorizontal];
  if (align && align !== "left") style.textAlign = align;

  const lh = node.lineHeight;
  if (lh && lh.unit === "PERCENT" && typeof lh.value === "number") {
    style.lineHeight = Math.round((lh.value / 100) * 1000) / 1000;
  } else if (lh && lh.unit === "PIXELS" && typeof lh.value === "number") {
    // PIXELS lineHeight is absolute ; LSML's lineHeight is unitless multiplier
    // — fall back to font-size-relative when both are known.
    if (node.fontSize) {
      style.lineHeight = Math.round((lh.value / node.fontSize) * 1000) / 1000;
    }
  }

  if (node.letterSpacing && node.letterSpacing.unit === "PIXELS") {
    style.letterSpacing = node.letterSpacing.value;
  }

  return style;
}

export type { MockTextNode };
