// Figma TEXT → LSML `text` (§4.4).
//
// The `bind.value` on the text primitive comes from the layer-name `[bind:...]`
// convention (see src/export/bindings.ts). When no binding is declared, the
// node's literal `characters` becomes the static value via the i18n-fallback
// pattern : we emit `metadata.literal` so authoring is round-trippable, and
// the runtime renders `characters` only when no binding is present.
//
// LSML 1.1 doesn't have a "static text" field — the canonical pattern is to
// emit a string LeafPath under `defaults.<auto-generated-path>`. For v0.1 we
// keep things simple : if a `[bind:value=...]` is present, we emit the bind ;
// otherwise we put the static string under `bind.value` is impossible (LeafPath
// must be a path, not a literal). So we synthesise a leaf path and have the
// caller (`bundle.ts`) plant the literal under `defaults`.

import type { TextPrimitive, TextStyle } from "~shared/lsml-types";
import { paintToSolidCss, type FigmaPaint } from "./color";
import { extractUniversal } from "./universal";
import { parseLayerName } from "../export/bindings";
import { PLUGIN_DATA_KEYS, PLUGIN_DATA_NAMESPACE } from "~shared/constants";
import { asArray, asNumber, asObject, asString } from "./figma-mixed";
import { withFigmaMetadata, type FigmaMetadata } from "./figma-metadata";
import { captureFigmaExtras } from "./figma-extras";
import type { MappingResult } from "./types";

interface MockTextNode {
  type: "TEXT";
  id: string;
  name: string;
  characters: string;
  width?: number;
  height?: number;
  x?: number;
  y?: number;
  fontSize?: number;
  fontWeight?: number;
  fontName?: { family: string; style: string };
  fills?: FigmaPaint[];
  textAlignHorizontal?: "LEFT" | "CENTER" | "RIGHT" | "JUSTIFIED";
  textCase?: "ORIGINAL" | "UPPER" | "LOWER" | "TITLE" | "SMALL_CAPS" | "SMALL_CAPS_FORCED";
  textAutoResize?: "NONE" | "WIDTH_AND_HEIGHT" | "HEIGHT" | "TRUNCATE";
  lineHeight?: { unit: "PIXELS" | "PERCENT" | "AUTO"; value?: number };
  letterSpacing?: { unit: "PIXELS" | "PERCENT"; value: number };
  visible?: boolean;
  opacity?: number;
  rotation?: number;
  layoutSizingHorizontal?: "FIXED" | "HUG" | "FILL";
  layoutSizingVertical?: "FIXED" | "HUG" | "FILL";
  /** Plugin data accessor (Figma SceneNode / mock surface). */
  getSharedPluginData?(namespace: string, key: string): string;
}

export interface TextMapOptions {
  parentRotation?: number;
  parentX?: number;
  parentY?: number;
}

const ALIGN_MAP: Record<string, TextStyle["textAlign"]> = {
  LEFT: "left",
  CENTER: "center",
  RIGHT: "right",
  JUSTIFIED: "justify",
};

export function mapText(node: MockTextNode, opts?: TextMapOptions): MappingResult {
  const parsed = parseLayerName(node.name, { primitiveKind: "text" });
  const style = extractStyle(node);

  // Roundtrip stability : when the node was just re-imported, plugin data
  // carries the original synthesised __lit.* path. Use it instead of the
  // node-id-derived synthesis (which would otherwise drift across imports).
  const preserved = readPluginData(node, PLUGIN_DATA_KEYS.litBindValue);
  const litPath = preserved ?? synthLiteralPath(node.id);

  const prim: TextPrimitive = {
    kind: "text",
    bind: parsed.bind ?? { value: litPath },
    ...extractUniversal(node, { parentRotation: opts?.parentRotation ?? 0 }),
  };
  // textCase → style.textTransform (LSML §4.4.1). Figma's UPPER/LOWER/TITLE
  // map directly. SMALL_CAPS / SMALL_CAPS_FORCED have no LSML equivalent
  // yet — preserve them in metadata.figma until the spec adds an enum.
  const tc = asString(node.textCase);
  if (tc) {
    const tt = textCaseToTransform(tc);
    if (tt) {
      style.textTransform = tt;
    } else if (tc === "SMALL_CAPS" || tc === "SMALL_CAPS_FORCED") {
      withFigmaMetadata(prim, { textCase: tc as "SMALL_CAPS" | "SMALL_CAPS_FORCED" });
    }
  }
  if (Object.keys(style).length > 0) prim.style = style;
  if (parsed.bindStyle) prim.bindStyle = parsed.bindStyle;
  if (parsed.bindUniversal) prim.bindUniversal = parsed.bindUniversal;

  // Universal `position` (LSML §5.4) — relative to parent's coordinate
  // origin. Non-zero only ; the root is at the document origin.
  const px = asNumber(node.x) ?? 0;
  const py = asNumber(node.y) ?? 0;
  const parentX = opts?.parentX ?? 0;
  const parentY = opts?.parentY ?? 0;
  const relX = roundTo3(px - parentX);
  const relY = roundTo3(py - parentY);
  if (relX !== 0 || relY !== 0) prim.position = { x: relX, y: relY };

  // textAutoResize and the raw fontName.style (e.g. "SemiBold Italic") have
  // no LSML representation — keep them in metadata.figma so the import
  // builder can pick the closest font variant on roundtrip.
  const figma: FigmaMetadata = {};
  const tar = asString(node.textAutoResize);
  if (tar && tar !== "NONE") {
    figma.textAutoResize = tar as Exclude<FigmaMetadata["textAutoResize"], undefined>;
  }
  const fontName = asObject<{ family: string; style: string }>(node.fontName);
  const fontStyleRaw = fontName ? asString(fontName.style) : undefined;
  if (fontStyleRaw) figma.fontStyle = fontStyleRaw;
  if (Object.keys(figma).length > 0) withFigmaMetadata(prim, figma);

  // Preserve the source Figma layer name (raw, including any [bind:...]
  // directive prefix) so the import side can restore it verbatim.
  if (node.name && node.name.trim().length > 0) {
    withFigmaMetadata(prim, { layerName: node.name });
  }

  // Text-specific authoring extras
  const textExtras: FigmaMetadata = {};
  const ps = asNumber((node as { paragraphSpacing?: unknown }).paragraphSpacing);
  if (ps !== undefined && ps !== 0) textExtras.paragraphSpacing = ps;
  const pi = asNumber((node as { paragraphIndent?: unknown }).paragraphIndent);
  if (pi !== undefined && pi !== 0) textExtras.paragraphIndent = pi;
  const tt = asString((node as { textTruncation?: unknown }).textTruncation);
  if (tt === "ENDING") textExtras.textTruncation = tt;
  const ml = asNumber((node as { maxLines?: unknown }).maxLines);
  if (ml !== undefined) textExtras.maxLines = ml;
  if (Object.keys(textExtras).length > 0) withFigmaMetadata(prim, textExtras);

  captureFigmaExtras(node as Parameters<typeof captureFigmaExtras>[0], prim);

  // When no [bind:...] directive is present, the node's `characters` is the
  // static text. We surface it via a synthesised leaf path that the bundle
  // assembler plants under `defaults`.
  if (!parsed.bind) {
    return {
      node: prim,
      defaults: { [litPath]: node.characters },
    };
  }
  return { node: prim };
}

function roundTo3(n: number): number {
  return Math.round(n * 1000) / 1000;
}

function textCaseToTransform(
  tc: string,
): "uppercase" | "lowercase" | "capitalize" | undefined {
  if (tc === "UPPER") return "uppercase";
  if (tc === "LOWER") return "lowercase";
  if (tc === "TITLE") return "capitalize";
  // ORIGINAL → omit. SMALL_CAPS / SMALL_CAPS_FORCED → caller falls back.
  return undefined;
}

function readPluginData(node: MockTextNode, key: string): string | null {
  if (typeof node.getSharedPluginData !== "function") return null;
  const v = node.getSharedPluginData(PLUGIN_DATA_NAMESPACE, key);
  return v === "" ? null : v;
}

export function synthLiteralPath(id: string): string {
  // Stable leaf path for static text. Two synthesis rules :
  //   - prefix : `__lit.text.` (reserved prefix, never collides with __inputs)
  //   - body   : Figma node id with non-path chars replaced by `_`
  return `__lit.text.${id.replace(/[^A-Za-z0-9_]/g, "_")}`;
}

function extractStyle(node: MockTextNode): TextStyle {
  // Figma returns `figma.mixed` (a Symbol) for any of these props when the
  // text node has multiple ranges with different values. asNumber / asString
  // / asObject collapse the Symbol back to undefined for safe consumption.
  const style: TextStyle = {};

  const fontSize = asNumber(node.fontSize);
  if (fontSize !== undefined) style.fontSize = fontSize;

  const fontWeight = asNumber(node.fontWeight);
  if (fontWeight !== undefined) style.fontWeight = fontWeight;

  const fontName = asObject<{ family: string; style: string }>(node.fontName);
  if (fontName) {
    const family = asString(fontName.family);
    if (family) style.fontFamily = family;
    const styleStr = asString(fontName.style);
    if (styleStr && /italic/i.test(styleStr)) style.fontStyle = "italic";
  }

  const fillsArr = asArray<FigmaPaint>(node.fills);
  const fill = fillsArr?.find((p) => p.type === "SOLID");
  if (fill) {
    const css = paintToSolidCss(fill);
    if (css) style.color = css;
  }

  const align = asString(node.textAlignHorizontal);
  if (align) {
    const mapped = ALIGN_MAP[align];
    if (mapped && mapped !== "left") style.textAlign = mapped;
  }

  const lh = asObject<{ unit: "PIXELS" | "PERCENT" | "AUTO"; value?: number }>(node.lineHeight);
  if (lh) {
    const lhValue = asNumber(lh.value);
    if (lh.unit === "PERCENT" && lhValue !== undefined) {
      style.lineHeight = Math.round((lhValue / 100) * 1000) / 1000;
    } else if (lh.unit === "PIXELS" && lhValue !== undefined && fontSize) {
      style.lineHeight = Math.round((lhValue / fontSize) * 1000) / 1000;
    }
  }

  const ls = asObject<{ unit: "PIXELS" | "PERCENT"; value: number }>(node.letterSpacing);
  if (ls && ls.unit === "PIXELS") {
    const lsValue = asNumber(ls.value);
    if (lsValue !== undefined) style.letterSpacing = lsValue;
  }

  return style;
}

export type { MockTextNode };
